### PR TITLE
List possible library types in command line options

### PR DESCRIPTION
**Pull request by casperboone**
This PR adds a list of the possible library types to the option description.

### CODE REVIEW

**Comment by FWDekker** [comment]
I think this change affects the README. Could you update the README?

**Comment by gandreadis** [comment]
@FWDekker Why should it affect the README? It only changes the error message that appears when the user enters an invalid library type (so no behavioral changes)

**Comment by gandreadis** [comment]
That being said, I do think that it would be useful to add all possible library types to the README.md, but I'll propose that as a separate PR (out of scope for this one).

**Comment by gandreadis** [comment]
Ah nevermind, I retract my earlier comment. @FWDekker, you're absolutely right, this deserves a README adaptation, as well.

**Pull request merged**
